image: alpine/edge
packages:
  - gcc
  - clang
  - meson
sources:
  - https://github.com/emersion/mrsh
tasks:
  - setup: |
      cd mrsh
      CC=gcc meson build-gcc
      CC=clang meson build-clang
  - build-gcc: |
      cd mrsh
      ninja -C build-gcc
  - build-clang: |
      cd mrsh
      ninja -C build-clang
  - test-gcc: |
      cd mrsh
      ninja -C build-gcc test
  - test-clang: |
      cd mrsh
      ninja -C build-clang test
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
