image: archlinux
packages:
  - gcc
  - meson
sources:
  - https://github.com/emersion/mrsh
tasks:
  - setup: |
      cd mrsh
      meson build -Db_sanitize=address,undefined
  - build: |
      cd mrsh
      ninja -C build
  - test: |
      cd mrsh
      ninja -C build test
  - build-no-readline: |
      cd mrsh
      meson configure build -Dreadline=disabled
      ninja -C build
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
